# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

inoutCppOpen <- function(sx, sy, vertices) {
    .Call('_SPIM_inoutCppOpen', PACKAGE = 'SPIM', sx, sy, vertices)
}

mcmc_Open_SPIM <- function(lam01, lam02, sigma, gamma, gammaprime, phi, D, lamd1, lamd2, yboth, yleft, yright, z, a, s1, s2, metamu, useverts, vertices, xlim, ylim, knownmatrix, Xidx, Xcpp, K, Ez, psi, N, proplam01, proplam02, propsig, propz, propgamma, props1x, props1y, props2x, props2y, propsigma_t, sigma_t, niter, nburn, nthin, npar, each, jointZ, zpossible, apossible, cancel, ID_L, ID_R, ones, twos, updates, swap, swaptol, Nfixed, left, right) {
    .Call('_SPIM_mcmc_Open_SPIM', PACKAGE = 'SPIM', lam01, lam02, sigma, gamma, gammaprime, phi, D, lamd1, lamd2, yboth, yleft, yright, z, a, s1, s2, metamu, useverts, vertices, xlim, ylim, knownmatrix, Xidx, Xcpp, K, Ez, psi, N, proplam01, proplam02, propsig, propz, propgamma, props1x, props1y, props2x, props2y, propsigma_t, sigma_t, niter, nburn, nthin, npar, each, jointZ, zpossible, apossible, cancel, ID_L, ID_R, ones, twos, updates, swap, swaptol, Nfixed, left, right)
}

inoutCpp <- function(sx, sy, vertices) {
    .Call('_SPIM_inoutCpp', PACKAGE = 'SPIM', sx, sy, vertices)
}

SCRlik <- function(z, lamd, y, K) {
    .Call('_SPIM_SCRlik', PACKAGE = 'SPIM', z, lamd, y, K)
}

calclamd <- function(lam, sigma, D) {
    .Call('_SPIM_calclamd', PACKAGE = 'SPIM', lam, sigma, D)
}

MCMC1 <- function(lam0, sigma, y, lamd, z, X, K, D, knownvector, s, psi, xlim, ylim, useverts, vertices, proplam0, propsigma, propsx, propsy, niter, nburn, nthin, obstype, tf, storeLatent) {
    .Call('_SPIM_MCMC1', PACKAGE = 'SPIM', lam0, sigma, y, lamd, z, X, K, D, knownvector, s, psi, xlim, ylim, useverts, vertices, proplam0, propsigma, propsx, propsy, niter, nburn, nthin, obstype, tf, storeLatent)
}

fulllik <- function(z, lamd1, lamd2, yboth, yleft, yright, X, K) {
    .Call('_SPIM_fulllik', PACKAGE = 'SPIM', z, lamd1, lamd2, yboth, yleft, yright, X, K)
}

MCMC2side <- function(lam01, lam02, sigma, lamd1, lamd2, y_both, y_left_true, y_right_true, y_left_obs, y_right_obs, z, X, tf, D, Nfixed, knownvector, ID_L, ID_R, swap, swaptol, s, psi, xlim, ylim, useverts, vertices, proplam01, proplam02, propsigma, propsx, propsy, niter, nburn, nthin, updates, storeLatent) {
    .Call('_SPIM_MCMC2side', PACKAGE = 'SPIM', lam01, lam02, sigma, lamd1, lamd2, y_both, y_left_true, y_right_true, y_left_obs, y_right_obs, z, X, tf, D, Nfixed, knownvector, ID_L, ID_R, swap, swaptol, s, psi, xlim, ylim, useverts, vertices, proplam01, proplam02, propsigma, propsx, propsy, niter, nburn, nthin, updates, storeLatent)
}

fullliktf <- function(z, lamd1, lamd2, yboth, yleft, yright, X, K, storeLatent) {
    .Call('_SPIM_fullliktf', PACKAGE = 'SPIM', z, lamd1, lamd2, yboth, yleft, yright, X, K, storeLatent)
}

MCMCtf2 <- function(lam01, lam02, sigma, lamd1, lamd2, y_both, y_left_true, y_right_true, y_left_obs, y_right_obs, z, X, tf1, tf2, D, Nfixed, knownvector, ID_L, ID_R, swap, swaptol, s, psi, xlim, ylim, useverts, vertices, proplam01, proplam02, propsigma, propsx, propsy, niter, nburn, nthin, updates, storeLatent) {
    .Call('_SPIM_MCMCtf2', PACKAGE = 'SPIM', lam01, lam02, sigma, lamd1, lamd2, y_both, y_left_true, y_right_true, y_left_obs, y_right_obs, z, X, tf1, tf2, D, Nfixed, knownvector, ID_L, ID_R, swap, swaptol, s, psi, xlim, ylim, useverts, vertices, proplam01, proplam02, propsigma, propsx, propsy, niter, nburn, nthin, updates, storeLatent)
}

fulllikInd <- function(z1, z2, lamd11, lamd21, lamd12, lamd22, yboth, yleft, yright, X, K, Nknown) {
    .Call('_SPIM_fulllikInd', PACKAGE = 'SPIM', z1, z2, lamd11, lamd21, lamd12, lamd22, yboth, yleft, yright, X, K, Nknown)
}

fulllikInd1D <- function(z1, z2, nth, Nfixed, lamd11, lamd21, lamd12, lamd22, yboth, yleft, yright, X, K) {
    .Call('_SPIM_fulllikInd1D', PACKAGE = 'SPIM', z1, z2, nth, Nfixed, lamd11, lamd21, lamd12, lamd22, yboth, yleft, yright, X, K)
}

updateparmsInd <- function(lam01, lam02, sigma, lamd11, lamd21, lamd12, lamd22, yboth, yleft, yright, z1, z2, X, K, D1, D2, Nfixed) {
    .Call('_SPIM_updateparmsInd', PACKAGE = 'SPIM', lam01, lam02, sigma, lamd11, lamd21, lamd12, lamd22, yboth, yleft, yright, z1, z2, X, K, D1, D2, Nfixed)
}

updatePsiInd <- function(z1, z2, capvector1, capvector2, lamd11, lamd12, lamd21, lamd22, yboth, yleft, yright, X, K, psi1, psi2, Nfixed) {
    .Call('_SPIM_updatePsiInd', PACKAGE = 'SPIM', z1, z2, capvector1, capvector2, lamd11, lamd12, lamd21, lamd22, yboth, yleft, yright, X, K, psi1, psi2, Nfixed)
}

updateACsInd <- function(z1, z2, s1, s2, xlim, ylim, useverts, vertices, D1, D2, lamd11, lamd21, lamd12, lamd22, lam01, lam02, sigma, yboth, yleft, yright, X, K, Nfixed) {
    .Call('_SPIM_updateACsInd', PACKAGE = 'SPIM', z1, z2, s1, s2, xlim, ylim, useverts, vertices, D1, D2, lamd11, lamd21, lamd12, lamd22, lam01, lam02, sigma, yboth, yleft, yright, X, K, Nfixed)
}

MCMCInd <- function(lam01, lam02, sigma, yboth, yleft, yright, z1, z2, X, K, D1, D2, Nfixed, capvector1, capvector2, s1, s2, psi1, psi2, xlim, ylim, useverts, vertices, proplam01, proplam02, propsigma, propsx, propsy, niter, nburn, nthin, updates) {
    .Call('_SPIM_MCMCInd', PACKAGE = 'SPIM', lam01, lam02, sigma, yboth, yleft, yright, z1, z2, X, K, D1, D2, Nfixed, capvector1, capvector2, s1, s2, psi1, psi2, xlim, ylim, useverts, vertices, proplam01, proplam02, propsigma, propsx, propsy, niter, nburn, nthin, updates)
}

fulllikInd2 <- function(z1, z2, lamdL, lamdR, yleft, yright, X, K) {
    .Call('_SPIM_fulllikInd2', PACKAGE = 'SPIM', z1, z2, lamdL, lamdR, yleft, yright, X, K)
}

fulllikInd1D2 <- function(z1, z2, lamdL, lamdR, yleft, yright, X, K) {
    .Call('_SPIM_fulllikInd1D2', PACKAGE = 'SPIM', z1, z2, lamdL, lamdR, yleft, yright, X, K)
}

updateparmsInd2 <- function(lam01, sigma, lamdL, lamdR, yleft, yright, z1, z2, X, K, D1, D2) {
    .Call('_SPIM_updateparmsInd2', PACKAGE = 'SPIM', lam01, sigma, lamdL, lamdR, yleft, yright, z1, z2, X, K, D1, D2)
}

updatePsiInd2 <- function(z1, z2, capvector1, capvector2, lamdL, lamdR, yleft, yright, X, K, psi1, psi2) {
    .Call('_SPIM_updatePsiInd2', PACKAGE = 'SPIM', z1, z2, capvector1, capvector2, lamdL, lamdR, yleft, yright, X, K, psi1, psi2)
}

updateACsInd2 <- function(z1, z2, s1, s2, xlim, ylim, D1, D2, lamdL, lamdR, lam01, sigma, yleft, yright, X, K) {
    .Call('_SPIM_updateACsInd2', PACKAGE = 'SPIM', z1, z2, s1, s2, xlim, ylim, D1, D2, lamdL, lamdR, lam01, sigma, yleft, yright, X, K)
}

MCMCInd2 <- function(lam01, sigma, yleft, yright, z1, z2, X, K, D1, D2, capvector1, capvector2, s1, s2, psi1, psi2, xlim, ylim, useverts, vertices, proplam01, propsigma, propsx, propsy, niter, nburn, nthin) {
    .Call('_SPIM_MCMCInd2', PACKAGE = 'SPIM', lam01, sigma, yleft, yright, z1, z2, X, K, D1, D2, capvector1, capvector2, s1, s2, psi1, psi2, xlim, ylim, useverts, vertices, proplam01, propsigma, propsx, propsy, niter, nburn, nthin)
}

fulllikInd3 <- function(z1, z2, z3, lamdB, lamdL, lamdR, yboth, yleft, yright, X, K) {
    .Call('_SPIM_fulllikInd3', PACKAGE = 'SPIM', z1, z2, z3, lamdB, lamdL, lamdR, yboth, yleft, yright, X, K)
}

fulllikInd1D3 <- function(z1, z2, z3, lamdB, lamdL, lamdR, yboth, yleft, yright, X, K) {
    .Call('_SPIM_fulllikInd1D3', PACKAGE = 'SPIM', z1, z2, z3, lamdB, lamdL, lamdR, yboth, yleft, yright, X, K)
}

MCMCInd3 <- function(lam01, lam02, sigma, yboth, yleft, yright, z1, z2, z3, X, K, D1, D2, D3, capvector1, capvector2, capvector3, s1, s2, s3, psi1, psi2, psi3, xlim, ylim, useverts, vertices, proplam01, proplam02, propsigma, propsx, propsy, niter, nburn, nthin) {
    .Call('_SPIM_MCMCInd3', PACKAGE = 'SPIM', lam01, lam02, sigma, yboth, yleft, yright, z1, z2, z3, X, K, D1, D2, D3, capvector1, capvector2, capvector3, s1, s2, s3, psi1, psi2, psi3, xlim, ylim, useverts, vertices, proplam01, proplam02, propsigma, propsx, propsy, niter, nburn, nthin)
}

upbeta <- function(beta0, beta1, grid, scell, propbeta0, propbeta1, EN, N, cellArea, z) {
    .Call('_SPIM_upbeta', PACKAGE = 'SPIM', beta0, beta1, grid, scell, propbeta0, propbeta1, EN, N, cellArea, z)
}

MCMC1b <- function(lam0, sigma, beta0, beta1, y, z, X, K, D, N, knownvector, s, scell, psi, grid, cellArea, EN, proplam0, propsigma, propbeta0, propbeta1, propsx, propsy, niter, nburn, nthin) {
    .Call('_SPIM_MCMC1b', PACKAGE = 'SPIM', lam0, sigma, beta0, beta1, y, z, X, K, D, N, knownvector, s, scell, psi, grid, cellArea, EN, proplam0, propsigma, propbeta0, propbeta1, propsx, propsy, niter, nburn, nthin)
}

MCMC2 <- function(lam01, lam02, sigma, beta0, beta1, yboth, yleft, yright, z, X, K, D, Nfixed, knownvector, ID_L, ID_R, swap, swaptol, left, right, s, scell, psi, grid, cellArea, EN, proplam01, proplam02, propsigma, propbeta0, propbeta1, propsx, propsy, niter, nburn, nthin, updates) {
    .Call('_SPIM_MCMC2', PACKAGE = 'SPIM', lam01, lam02, sigma, beta0, beta1, yboth, yleft, yright, z, X, K, D, Nfixed, knownvector, ID_L, ID_R, swap, swaptol, left, right, s, scell, psi, grid, cellArea, EN, proplam01, proplam02, propsigma, propbeta0, propbeta1, propsx, propsy, niter, nburn, nthin, updates)
}

intlikRcpp <- function(parm, ymat, X, K, G, D, n) {
    .Call('_SPIM_intlikRcpp', PACKAGE = 'SPIM', parm, ymat, X, K, G, D, n)
}

findPossible2D <- function(z, G_true, G_obs_true, M, ncat) {
    .Call('_SPIM_findPossible2D', PACKAGE = 'SPIM', z, G_true, G_obs_true, M, ncat)
}

arma_setdiff <- function(x, y) {
    .Call('_SPIM_arma_setdiff', PACKAGE = 'SPIM', x, y)
}

