# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

inoutCpp <- function(sx, sy, vertices) {
    .Call('_SPIM_inoutCpp', PACKAGE = 'SPIM', sx, sy, vertices)
}

MCMC1 <- function(lam0, sigma, y, lamd, z, X, K, D, knownvector, s, psi, xlim, ylim, useverts, vertices, proplam0, propsigma, propsx, propsy, niter, nburn, nthin, obstype, tf, storeLatent) {
    .Call('_SPIM_MCMC1', PACKAGE = 'SPIM', lam0, sigma, y, lamd, z, X, K, D, knownvector, s, psi, xlim, ylim, useverts, vertices, proplam0, propsigma, propsx, propsy, niter, nburn, nthin, obstype, tf, storeLatent)
}

MCMC2side <- function(lam01, lam02, sigma, lamd1, lamd2, y_both, y_left_true, y_right_true, y_left_obs, y_right_obs, z, X, tf, D, Nfixed, knownvector, ID_L, ID_R, swap, swaptol, s, psi, xlim, ylim, useverts, vertices, proplam01, proplam02, propsigma, propsx, propsy, niter, nburn, nthin, updates, storeLatent) {
    .Call('_SPIM_MCMC2side', PACKAGE = 'SPIM', lam01, lam02, sigma, lamd1, lamd2, y_both, y_left_true, y_right_true, y_left_obs, y_right_obs, z, X, tf, D, Nfixed, knownvector, ID_L, ID_R, swap, swaptol, s, psi, xlim, ylim, useverts, vertices, proplam01, proplam02, propsigma, propsx, propsy, niter, nburn, nthin, updates, storeLatent)
}

MCMCtf2 <- function(lam01, lam02, sigma, lamd1, lamd2, y_both, y_left_true, y_right_true, y_left_obs, y_right_obs, z, X, tf1, tf2, D, Nfixed, knownvector, ID_L, ID_R, swap, swaptol, s, psi, xlim, ylim, useverts, vertices, proplam01, proplam02, propsigma, propsx, propsy, niter, nburn, nthin, updates, storeLatent) {
    .Call('_SPIM_MCMCtf2', PACKAGE = 'SPIM', lam01, lam02, sigma, lamd1, lamd2, y_both, y_left_true, y_right_true, y_left_obs, y_right_obs, z, X, tf1, tf2, D, Nfixed, knownvector, ID_L, ID_R, swap, swaptol, s, psi, xlim, ylim, useverts, vertices, proplam01, proplam02, propsigma, propsx, propsy, niter, nburn, nthin, updates, storeLatent)
}

HazACup <- function(y, pd, X, D, s, z, ll_y_curr, beta0, beta1, sigma, M, J, tf, props, xlim, ylim) {
    .Call('_SPIM_HazACup', PACKAGE = 'SPIM', y, pd, X, D, s, z, ll_y_curr, beta0, beta1, sigma, M, J, tf, props, xlim, ylim)
}

intlikRcpp <- function(parm, ymat, X, K, G, D, n) {
    .Call('_SPIM_intlikRcpp', PACKAGE = 'SPIM', parm, ymat, X, K, G, D, n)
}

findPossible2D <- function(z, G_true, G_obs_true, M, ncat) {
    .Call('_SPIM_findPossible2D', PACKAGE = 'SPIM', z, G_true, G_obs_true, M, ncat)
}

arma_setdiff <- function(x, y) {
    .Call('_SPIM_arma_setdiff', PACKAGE = 'SPIM', x, y)
}

indLL <- function(z, yI, yP, lambdaI, ID) {
    .Call('_SPIM_indLL', PACKAGE = 'SPIM', z, yI, yP, lambdaI, ID)
}

siteup <- function(z1, z2, yI, yP, samp_mat, lambdaI, packID, ll_yi, ll_yp, lamd) {
    .Call('_SPIM_siteup', PACKAGE = 'SPIM', z1, z2, yI, yP, samp_mat, lambdaI, packID, ll_yi, ll_yp, lamd)
}

calcllyevent <- function(y_true, y_event, Xcov3D, pi1, pi2, pi3, z, M, J, K) {
    .Call('_SPIM_calcllyevent', PACKAGE = 'SPIM', y_true, y_event, Xcov3D, pi1, pi2, pi3, z, M, J, K)
}

calcllyevent2D <- function(y_true, y_event, Xcov3D, pi1, pi2, pi3, J, K) {
    .Call('_SPIM_calcllyevent2D', PACKAGE = 'SPIM', y_true, y_event, Xcov3D, pi1, pi2, pi3, J, K)
}

occDepUp <- function(occidx, pd, upOcc, y_true, y_Occ_true, y_SCR, y_event, pi1, pi2, pi3, ll_y, ll_y_event, z, M, J, K) {
    .Call('_SPIM_occDepUp', PACKAGE = 'SPIM', occidx, pd, upOcc, y_true, y_Occ_true, y_SCR, y_event, pi1, pi2, pi3, ll_y, ll_y_event, z, M, J, K)
}

occDepUpMbradius <- function(occidx, s, X, pd, upDist, y_true, y_Occ_true, y_SCR, y_event, pi1, pi2, pi3, ll_y, ll_y_event, state, linp_p0, p0, beta_p0, sex, Xcov3D1, Xcov3D2, D, z, sigma, M, J, K) {
    .Call('_SPIM_occDepUpMbradius', PACKAGE = 'SPIM', occidx, s, X, pd, upDist, y_true, y_Occ_true, y_SCR, y_event, pi1, pi2, pi3, ll_y, ll_y_event, state, linp_p0, p0, beta_p0, sex, Xcov3D1, Xcov3D2, D, z, sigma, M, J, K)
}

occDepUpMb4Dradius <- function(occidx, s, X, pd, upDist, y_true, y_Occ_true, y_SCR, y_event, pi1, pi2, pi3, ll_y, ll_y_event, state, linp_p0, p0, beta_p0, sex, Xcov3D1, Xcov3D2, D, z, sigma, M, J, K) {
    .Call('_SPIM_occDepUpMb4Dradius', PACKAGE = 'SPIM', occidx, s, X, pd, upDist, y_true, y_Occ_true, y_SCR, y_event, pi1, pi2, pi3, ll_y, ll_y_event, state, linp_p0, p0, beta_p0, sex, Xcov3D1, Xcov3D2, D, z, sigma, M, J, K)
}

occDepUpRadius <- function(occidx, s, X, pd, upDist, y_true, y_Occ_true, y_SCR, y_event, pi1, pi2, pi3, ll_y, ll_y_event, z, M, J, K) {
    .Call('_SPIM_occDepUpRadius', PACKAGE = 'SPIM', occidx, s, X, pd, upDist, y_true, y_Occ_true, y_SCR, y_event, pi1, pi2, pi3, ll_y, ll_y_event, z, M, J, K)
}

typeCount <- function(ncat, nrep, nlevels, locustype, ptype, G_obs_true, G_obs) {
    .Call('_SPIM_typeCount', PACKAGE = 'SPIM', ncat, nrep, nlevels, locustype, ptype, G_obs_true, G_obs)
}

typeCountSamptype <- function(ncat, nrep, nlevels, locustype, ptype, G_obs_true, G_obs, samptype, samplevels) {
    .Call('_SPIM_typeCountSamptype', PACKAGE = 'SPIM', ncat, nrep, nlevels, locustype, ptype, G_obs_true, G_obs, samptype, samplevels)
}

